"""add_branch_model

Revision ID: 2bdfef4fa6b6
Revises: 21ca69483103
Create Date: 2025-09-24 19:30:08.256475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bdfef4fa6b6'
down_revision = '21ca69483103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_key', sa.String(length=64), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_payment_session', type_='foreignkey')
        batch_op.drop_column('payment_session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_session_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_payments_payment_session', 'payment_sessions', ['payment_session_id'], ['id'])

    with op.batch_alter_table('client_api_keys', schema=None) as batch_op:
        batch_op.drop_column('secret_key')

    # ### end Alembic commands ###
