"""add admin notifications

Revision ID: d013b60aeca4
Revises: a2605353ae90
Create Date: 2025-09-25 18:09:34.800264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd013b60aeca4'
down_revision = 'a2605353ae90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superadmin_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_clients', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_commission', sa.Numeric(precision=20, scale=8), nullable=True))
        batch_op.drop_constraint('fk_branches_adminuser_id', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['superadmin_id'], ['id'])
        batch_op.drop_column('api_key')
        batch_op.drop_column('api_secret')
        batch_op.drop_column('adminuser_id')
        batch_op.drop_column('client_id')
        batch_op.drop_column('webhook_url')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('wallet_balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False))
        batch_op.drop_constraint('unique_provider_balance', type_='unique')
        batch_op.create_unique_constraint('unique_provider_balance', ['provider_id', 'currency'])
        batch_op.drop_column('currency_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_code', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint('unique_provider_balance', type_='unique')
        batch_op.create_unique_constraint('unique_provider_balance', ['provider_id', 'currency_code'])
        batch_op.drop_column('currency')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('adminuser_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('api_secret', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('api_key', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])
        batch_op.create_foreign_key('fk_branches_adminuser_id', 'admin_users', ['adminuser_id'], ['id'])
        batch_op.drop_column('monthly_commission')
        batch_op.drop_column('total_clients')
        batch_op.drop_column('superadmin_id')

    # ### end Alembic commands ###
